### PR TITLE
ENG-2324 Add "Software" tag to PNG

### PR DESCRIPTION
**Pull request by frankleonrose**
- [x] Add Software: scrcpy/version to PNG
- [x] Use mobot.mk Makefile build on Daisy
- [x] Make build on Screen Server NUC, too!

```
cd scrcpy
make -f mobot.mk
```

### CODE REVIEW

**Review by jcorrado — CHANGES_REQUESTED** [review]
Can we create some cascading targets for cleaning and installation, so one doesn't have to drop down to meson/ninja

**Comment by frankleonrose** [comment]
@jcorrado Do you mean adding the following? Or something more elaborate?
```
clean:
	rm -rf build-ffmpeg build-libav build-app

install: scrcpy
	sudo ninja -Cbuild-app install
```

**Comment by jcorrado** [comment]
> @jcorrado Do you mean adding the following? Or something more elaborate?
> 
> ```
> clean:
> 	rm -rf build-ffmpeg build-libav build-app
> 
> install: scrcpy
> 	sudo ninja -Cbuild-app install
> ```

Simple targets like that are all we need!  (But no `sudo`, please - the caller should invoke `make` with `sudo` for the installation target).

**Comment by frankleonrose** [comment]
Thanks very much for the feedback.

**Pull request merged**
